import { USER_ROLES } from './roles'

export const PERMISSIONS = {
  // FINANZAS
  FINANZAS_VIEW: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR],
  FINANZAS_EDIT: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR],
  
  // ACTIVIDADES
  ACTIVIDADES_VIEW: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR, USER_ROLES.TECNICO, USER_ROLES.OPERADOR],
  ACTIVIDADES_CREATE: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR, USER_ROLES.TECNICO],
  ACTIVIDADES_EDIT: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR, USER_ROLES.TECNICO],
  ACTIVIDADES_EXECUTE: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR, USER_ROLES.TECNICO, USER_ROLES.OPERADOR], // Bitacora

  // PROGRAMACIONES
  PROGRAMACIONES_VIEW: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR, USER_ROLES.TECNICO, USER_ROLES.OPERADOR],
  PROGRAMACIONES_EDIT: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR, USER_ROLES.TECNICO],

  // CONFIGURACION
  CONFIG_HACIENDA: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR],

  // MAPAS Y ZONAS
  ZONAS_VIEW: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR, USER_ROLES.TECNICO, USER_ROLES.OPERADOR],
  ZONAS_EDIT: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR, USER_ROLES.TECNICO],

  // ADMINISTRACION
  USERS_MANAGE: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR],
  HACIENDAS_MANAGE: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR],
  ASESORES_MANAGE: [USER_ROLES.SUPERADMIN],
  SYSTEM_SETTINGS: [USER_ROLES.SUPERADMIN],
  SUBSCRIPTIONS_MANAGE: [USER_ROLES.SUPERADMIN],
  
  // BITACORA
  BITACORA_EDIT: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR, USER_ROLES.TECNICO],

  // HACIENDA CONFIG
  HACIENDA_OPENROUTER_VIEW: [USER_ROLES.SUPERADMIN, USER_ROLES.ADMINISTRADOR]
}

export function hasPermission(userRole, requiredRoles) {
  if (!userRole) return false
  if (!Array.isArray(requiredRoles)) {
    requiredRoles = [requiredRoles]
  }
  const normalizedRole = String(userRole).toLowerCase()
  
  // SuperAdmin override explicitly handled here as well as by including it in the arrays above
  if (normalizedRole === USER_ROLES.SUPERADMIN || normalizedRole === 'superadmin') {
    return true
  }
  
  if (normalizedRole === USER_ROLES.ADMINISTRADOR || normalizedRole === 'admin') {
    return true
  }

  return requiredRoles.includes(userRole) || requiredRoles.includes(normalizedRole)
}
